# Generated by Django 2.1.5 on 2019-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(height_field=300, null=True, upload_to='C:\\Users\\Bohdan\\PycharmProjects\\restFull\\media/', width_field=300),
        ),
    ]
