# Generated by Django 2.1.5 on 2019-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='C:\\Users\\Bohdan\\PycharmProjects\\restFull\\media/', width_field=300),
        ),
    ]
